networks:
  cometbft_network:
    driver: bridge

services:
  node0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cometbft-node0
    environment:
      - NODE_MONIKER=node0
      - CMT_HOME=/root/.cometbft
      - HTTP_PORT=5000
    ports:
      - "9000:9000" # P2P port
      - "9001:9001" # RPC port
      - "5000:5000" # HTTP port
    volumes:
      - ./node0:/root/.cometbft
    networks:
      - cometbft_network

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cometbft-node1
    environment:
      - NODE_MONIKER=node1
      - CMT_HOME=/root/.cometbft
      - HTTP_PORT=5001
    ports:
      - "9002:9002" # P2P port
      - "9003:9003" # RPC port
      - "5001:5001" # HTTP port
    volumes:
      - ./node1:/root/.cometbft
    networks:
      - cometbft_network
    depends_on:
      - node0

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cometbft-node2
    environment:
      - NODE_MONIKER=node2
      - CMT_HOME=/root/.cometbft
      - HTTP_PORT=5002
    ports:
      - "9004:9004" # P2P port
      - "9005:9005" # RPC port
      - "5002:5002" # HTTP port
    volumes:
      - ./node2:/root/.cometbft
    networks:
      - cometbft_network
    depends_on:
      - node0

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cometbft-node3
    environment:
      - NODE_MONIKER=node3
      - CMT_HOME=/root/.cometbft
      - HTTP_PORT=5003
    ports:
      - "9006:9006" # P2P port
      - "9007:9007" # RPC port
      - "5003:5003" # HTTP port
    volumes:
      - ./node3:/root/.cometbft
    networks:
      - cometbft_network
    depends_on:
      - node0